# This is a basic workflow
name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  buil:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo WORKSPACE ${{github.workspace}}

      # Install Node v20.9.0
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Run Tests
        run: yarn test
